version: '3.8'

services:
  db:
    image: postgres:14.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
        - "8000:8000"
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
volumes:
  static_value:
  postgres_data: